embed_assets: on

javascripts:
    application:
        - assets/scripts/common.js
        - assets/scripts/plugins/jquery.jnotify.js
        - assets/scripts/public.js
    admin:
        - assets/scripts/common.js
        - assets/scripts/libs/bootstrap/bootstrap-alert.min.js
        - assets/scripts/libs/bootstrap/bootstrap-button.min.js
        - assets/scripts/libs/bootstrap/bootstrap-carousel.min.js
        - assets/scripts/libs/bootstrap/bootstrap-collapse.min.js
        - assets/scripts/libs/bootstrap/bootstrap-dropdown.min.js
        - assets/scripts/libs/bootstrap/bootstrap-modal.min.js
        - assets/scripts/libs/bootstrap/bootstrap-tooltip.min.js
        - assets/scripts/libs/bootstrap/bootstrap-popover.min.js
        - assets/scripts/libs/bootstrap/bootstrap-scrollspy.min.js
        - assets/scripts/libs/bootstrap/bootstrap-tab.min.js
        - assets/scripts/libs/bootstrap/bootstrap-transition.min.js
        - assets/scripts/libs/bootstrap/bootstrap-typeahead.min.js
        - assets/scripts/plugins/jquery.jnotify.js
        - assets/scripts/plugins/bootstrap/bootstrap-datepicker.js
        - assets/scripts/plugins/bootstrap/bootstrap-timepicker.js
        - assets/scripts/plugins/wysihtml5-0.3.0_rc2.js
        - assets/scripts/plugins/bootstrap/bootstrap-wysihtml5.js
        - assets/scripts/plugins/bootstrap/bootstrap-tagcomplete.js
        - assets/scripts/plugins/jquery.dataTables.min.js
        - assets/scripts/plugins/paging.js
        - assets/scripts/plugins/jquery.form.js
        - assets/scripts/plugins/jquery.color.js
        - assets/scripts/plugins/jquery.Jcrop.js
        - assets/scripts/admin_utils.js
